// - - - - - - ERRORS - - - - - - 
#define ERR_NEEDMOREPARAMS(nick, cmd) ": 461 " + nick + " " + cmd + " :Need more parameters\r\n"
#define ERR_PASSWDMISMATCH(nick) ": 464 " + nick + " :Invalid password\r\n"
#define ERR_ALREADYREGISTERED(nick) ": 462 " + nick + " :You may not reregister\r\n"
#define ERR_NOTREGISTERED(nick) ": 451 :You have not Registered\r\n"
#define ERR_NONICKNAMEGIVEN(nick) ": 431 " + nick + " :No Nickname Given\r\n"
#define ERR_NICKNAMEINUSE(nick, attempt) ": 433 " + nick + " " + attempt + " :Nickname in use.\r\n"
#define ERR_ERRONEUSNICKNAME(nick, attempt) ": 432 " + nick + " " + attempt + " :Erroneus nickname\r\n"
#define ERR_UNKNOWNCOMMAND(nick, cmd) ": 421 " + nick + " " + cmd + " :Unknown command\r\n"

#define ERR_BANNEDFROMCHAN(nick) ": 474 " + nick + " :You are banned from this channel\n"
#define ERR_BADCHANNELKEY(client, channel) ": 476 " + client + " " + channel + " :Cannot join channel (+k)\r\n"
#define ERR_INVITEONLYCHAN(nick, channel) ": 473 " + nick + " " + channel + " :Cannot join channel (+i)\r\n"
#define ERR_CHANNELISFULL(nick, channel) ": 471 " + nick + " " + channel + " :Cannot join channel (+l)\r\n"
#define ERR_BADCHANMASK(channel) ": 476 " + channel + " :Bad Channel Mask\n"
#define ERR_NOSUCHCHANNEL(nick, channel) ": 403 " + nick + " " + channel + " :No such channel\r\n"
#define ERR_NOTONCHANNEL(nick, channel) ": 442 " + nick + " " + channel + " :You're not in the channel\r\n"
#define ERR_CANNOTSENDTOCHAN(nick, channel) ": 404 " + nick + " " + channel + " :Cannot send to channel\r\n"
#define ERR_NOTEXTTOSEND(nick) ": 412 " + nick + " :No text to send\r\n"
#define ERR_INVALIDEMODEPARAM(nick, channel, mode) ": 696 " + nick + " " + channel + " :" + msg + "\r\n"
#define ERR_USERONCHANNEL(nick, channel_name) ": 443 " + nick + " " + channel_name + " :is already on channel\r\n"
#define ERR_NOSUCHNICK(nick, noexist) ": 401 " + nick + " " + noexist + " :No such nick\r\n"
#define ERR_CHANOPRIVSNEEDED(nick, channel_name) ": 482 " + nick + " " + channel_name + " : You're not channel operator\r\n"
#define ERR_USERNOTINCHANNEL(nick, target, channel_name) ": 441 " + nick + " "  + target + " " + channel_name + " :They aren't on that channel\r\n"
#define ERR_UNKNOWNMODE(nick, cmd) ": 472 " + nick + " " + cmd + ": is unknown mode\r\n"

//// - - - - - - REPLIES - - - - - - 
#define RPL_WELCOME(nick, prefix) ":" + prefix + " 001 " + nick + " :Welcome " + nick + " to the ft_irc\r\n"
#define RPL_NOTOPIC(nick, channel) ": 331 " + nick + " " + channel + " :No topic is set\r\n"
#define RPL_TOPIC(nick, channel ,topic) ": 332 " + nick + " " + channel + " " + topic + "\r\n"
#define RPL_TOPICWHOTIME(client, channel, nick, setat) ": 333 " + client + " " + channel + " " + nick + " :" + setat + "\r\n"
#define RPL_UMODEIS(client, modes) " : 221"
#define RPL_WHOREPLY(client, channel, username, host, nick, realname) ": 352 " + client + " " + channel + " " + username + " " + host + " my net " + nick + " H@ :0 " + realname + "\r\n"
#define RPL_ENDOFWHO(client, channel) ": 315 " + client + " " + channel + " :End of WHO list\r\n"
#define KICK_MSG(nick, channel_name, target, reason) ":" + nick + " KICK " + channel_name + " " + target + reason + "\r\n"
#define TOPIC_CHANGE(nick, channel, topic) ":" + nick + " TOPIC " + channel + " " + topic + "\r\n"
#define RPL_INVITING(target, channel_name, client) ": 341 " + client + " " + target + " " + channel_name + " : \r\n" //TALVEZ PRECISE DE MSG (AMAURI)
#define RPL_INVITED(channel, client) "You have been invited to " + channel + " by " + client + "\r\n"
#define RPL_CHANNELMODEIS(nick, channel, modes) ": 324 " + nick + " " + channel + " " + modes + "\r\n"
#define MODE(nick, channel, status) ":" + nick + " MODE " + channel + " :" + status + "\r\n"
#define SET_KEY(nick, channel, cmd, key) ":" + nick + " MODE " + channel + " " + cmd + " :" + key + "\r\n"
#define MODE_OPERATOR(nick, channel, cmd, target) ":" + nick + " MODE " + channel + " " + cmd + " :" + target + "\r\n"

#define RPL_JOIN(nick, channel) ":" + nick + " JOIN " + channel + "\r\n"
#define RPL_PRIVMSG(nick, target, msg) ":" + nick + " PRIVMSG " + target + " :" + msg + "\r\n"

#define RPL_NAMREPLY(client, channel, names) ": 353 " + client + " = " + channel + " :" + names + "\r\n"

